

class biomes_module(object):
    
    def __init__(self, loc):
        
        self.loc = loc
        
        self.data_dict = {
                            "biomes" : {
                                        "y0"         : 1998, 
                                        "y1"         : 2010,  
                                        "dir"        : f"{loc}",
                                        "file"       : "Time_Varying_Biomes",
                                        "area_units" : "1e6 km2",
                                        "area_ocean" : 361.0,
                                        "notes" : "Global Ocean Biomes as per Fay and McKinley (2014)), downloaded from: doi:10.1594/PANGAEA.828650"
                                      },            
                          }
        
        self.biomes_dict = {
                 1 : { 'label'     : 'NP_ICE',
                       'mean_area' : 4.5852,
                       'core_area' : 3.9112,
                     },
                 2 : { 'label'     : 'NP_SPSS',
                       'mean_area' : 12.838,
                       'core_area' : 8.7063,
                     },
                 3 : { 'label'     : 'NP_STSS',
                       'mean_area' : 6.8257,
                       'core_area' : 4.3398,
                     },
                 4 : { 'label'     : 'NP_STPS',
                       'mean_area' : 41.048,
                       'core_area' : 31.305,
                     },
                 5 : { 'label'     : 'P_EQU_W', #'Pac_EQU_W',
                       'mean_area' : 11.593,
                       'core_area' : 4.9040,
                     },
                 6 : { 'label'     : 'P_EQU_E',#'Pac_EQU_E',
                       'mean_area' : 14.890,
                       'core_area' : 7.7117,
                     },
                 7 : { 'label'     : 'SP_STPS',
                       'mean_area' : 52.705,
                       'core_area' : 43.067,
                     },
                 8 : { 'label'     : 'NA_ICE',
                       'mean_area' : 5.4750,
                       'core_area' : 4.6123,
                     },
                 9 : { 'label'     : 'NA_SPSS',
                       'mean_area' : 10.062,
                       'core_area' : 7.8048,
                     },
                 10 : { 'label'    : 'NA_STSS',
                       'mean_area' : 5.9744,
                       'core_area' : 4.6178,
                     },
                 11 : { 'label'    : 'NA_STPS',
                       'mean_area' : 17.464,
                       'core_area' : 13.746,
                     },
                 12 : { 'label'    : 'A_EQU', #'Atl_EQU',
                       'mean_area' : 7.4147,
                       'core_area' : 3.1972,
                     },
                 13 : { 'label'    : 'SA_STPS',
                       'mean_area' : 18.055,
                       'core_area' : 16.056,
                     },
                 14 : { 'label'    : 'IND_STPS',
                       'mean_area' : 35.936,
                       'core_area' : 32.383,
                     },
                 15 : { 'label'    : 'SO_STSS',
                       'mean_area' : 29.692,
                       'core_area' : 23.670,
                     },
                 16 : { 'label'    : 'SO_SPSS',
                       'mean_area' : 30.628,
                       'core_area' : 25.875,
                     },
                 17 : { 'label'    : 'SO_ICE',
                       'mean_area' : 18.678,
                       'core_area' : 16.169,
                     }
               }    
        
        self.dict_biomes_plot = {
                 1 : { 'label'        : 'NP_ICE',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.4,
                       'ts_rmse_avg_ymax'     : 1.,
                       'ts_corr_avg_ymin'     : 0.1, 
                       'ts_corr_avg_ymax'     : 0.5,
                     },
                 2 : { 'label'     : 'NP_SPSS',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.3,
                       'ts_rmse_avg_ymax'     : 1.5,
                       'ts_corr_avg_ymin'     : 0.1, 
                       'ts_corr_avg_ymax'     : 0.7,

                     },
                 3 : { 'label'     : 'NP_STSS',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.,
                       'ts_rmse_avg_ymax'     : 2.5,
                       'ts_corr_avg_ymin'     : -0.3, 
                       'ts_corr_avg_ymax'     : 0.5,
                     },
                 4 : { 'label'     : 'NP_STPS',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.1,
                       'ts_rmse_avg_ymax'     : .5,
                       'ts_corr_avg_ymin'     : -.1, 
                       'ts_corr_avg_ymax'     : 0.4,
                     },
                 5 : { 'label'     : 'Pac_EQU_W',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.,
                       'ts_rmse_avg_ymax'     : .7,
                       'ts_corr_avg_ymin'     : 0., 
                       'ts_corr_avg_ymax'     : 0.5,
                     },
                 6 : { 'label'     : 'Pac_EQU_E',
                       'ts_clim_mean_ymin'    : 1.,
                       'ts_clim_mean_ymax'    : 3.5,
                       'ts_clim_var_ymin'     : 0.,
                       'ts_clim_var_ymax'     : 0.8,
                       'ts_avg_ymin'        : 0.9e13,
                       'ts_avg_ymax'        : 2.5e13,
                       'ts_avg_rmse_ymin'   : 0.1, 
                       'ts_avg_rmse_ymax'   : 0.4,
                       'ts_avg_corr_ymin'   : -.4, 
                       'ts_avg_corr_ymax'   : .8, 
                       'ts_rmse_avg_ymin'     : .3,
                       'ts_rmse_avg_ymax'     : 1.1,
                       'ts_corr_avg_ymin'     : -0.2, 
                       'ts_corr_avg_ymax'     : 0.6, 
                     },
                 7 : { 'label'     : 'SP_STPS',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.,
                       'ts_rmse_avg_ymax'     : 1.,
                       'ts_corr_avg_ymin'     : 0.2, 
                       'ts_corr_avg_ymax'     : 0.6,
                     },
                 8 : { 'label'     : 'NA_ICE',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.2,
                       'ts_rmse_avg_ymax'     : 1.6,
                       'ts_corr_avg_ymin'     : 0.2, 
                       'ts_corr_avg_ymax'     : 0.5,
                     },
                 9 : { 'label'     : 'NA_SPSS',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.4,
                       'ts_rmse_avg_ymax'     : 1.8,
                       'ts_corr_avg_ymin'     : 0., 
                       'ts_corr_avg_ymax'     : 0.8,
                     },
                 10 : { 'label'     : 'NA_STSS',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.1,
                       'ts_rmse_avg_ymax'     : 1.6,
                       'ts_corr_avg_ymin'     : 0.2, 
                       'ts_corr_avg_ymax'     : 0.8,
                     },
                 11 : { 'label'    : 'NA_STPS',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.1,
                       'ts_rmse_avg_ymax'     : 0.4,
                       'ts_corr_avg_ymin'     : 0., 
                       'ts_corr_avg_ymax'     : 0.5,
                     },
                 12 : { 'label'    : 'Atl_EQU',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.,
                       'ts_rmse_avg_ymax'     : .4,
                       'ts_corr_avg_ymin'     : 0., 
                       'ts_corr_avg_ymax'     : 0.7,
                     },
                 13 : { 'label'    : 'SA_STPS',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.,
                       'ts_rmse_avg_ymax'     : 1.2,
                       'ts_corr_avg_ymin'     : 0., 
                       'ts_corr_avg_ymax'     : 0.6,
                     },
                 14 : { 'label'    : 'IND_STPS',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.1,
                       'ts_rmse_avg_ymax'     : .6,
                       'ts_corr_avg_ymin'     : 0.1, 
                       'ts_corr_avg_ymax'     : 0.6,
                     },
                 15 : { 'label'     : 'SO_STSS',
                       'ts_clim_mean_ymin'    : -2.5,
                       'ts_clim_mean_ymax'    : 1.1,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : 1.4,
                       'ts_avg_ymin'        : -.7e14, 
                       'ts_avg_ymax'        : 0.,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 1.,
                       'ts_avg_corr_ymin'   : 0.4, 
                       'ts_avg_corr_ymax'   : 1., 
                       'ts_rmse_avg_ymin'     : 0.,
                       'ts_rmse_avg_ymax'     : 2., 
                       'ts_corr_avg_ymin'     : 0.2, 
                       'ts_corr_avg_ymax'     : 0.8,
                     },
                 16 : { 'label'    : 'SO_SPSS',
                       'ts_clim_mean_ymin'    : -1.5,
                       'ts_clim_mean_ymax'    : 2.5,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .6,
                       'ts_avg_ymin'        : -3e13,
                       'ts_avg_ymax'        : 2e13,
                       'ts_avg_rmse_ymin'   : 8,
                       'ts_avg_rmse_ymax'   : 33,
                       'ts_avg_corr_ymin'   : -.3, 
                       'ts_avg_corr_ymax'   : 1., 
                       'ts_rmse_avg_ymin'     : .2,
                       'ts_rmse_avg_ymax'     : 1.2,
                       'ts_corr_avg_ymin'     : 0., 
                       'ts_corr_avg_ymax'     : .8,
                     },
                 17 : { 'label'    : 'SO_ICE',
                       'ts_clim_mean_ymin'    : -.05,
                       'ts_clim_mean_ymax'    : 1.,
                       'ts_clim_var_ymin'     : 0,
                       'ts_clim_var_ymax'     : .3,
                       'ts_avg_ymin'        : -1e12,
                       'ts_avg_ymax'        : 4e12,
                       'ts_avg_rmse_ymin'   : 0.,
                       'ts_avg_rmse_ymax'   : 10.,
                       'ts_avg_corr_ymin'   : 0., 
                       'ts_avg_corr_ymax'   : .7, 
                       'ts_rmse_avg_ymin'     : 0.2,
                       'ts_rmse_avg_ymax'     : 0.7,
                       'ts_corr_avg_ymin'     : -.1, 
                       'ts_corr_avg_ymax'     : 0.5,
                     }
               }    
    
    def PrintLoc(self):
        print(self.loc)

      
