user_data_root: /space/hall5/sitestore/eccc/crd/ccrn/users/rpg002/data

var_list:
  - mlotst
realm_list:
  - Omon

model: CanESM5
regrid: True
lev_range: 600

historical: True
historical_initial_year: 1950
historical_final_year: 2025

assimilation: False
assimilation_extracted_from_disc: False
extention_years: [2021,2024]

hindcast: False
historical_initial_year: 1950
historical_final_year: 2025

realizations:
  - r1i1p2f1


cmip6_root: /space/hall5/sitestore/eccc/crd/ccrn/model_output/CMIP6/final/CMIP6
canoe_bgc_root: /space/hall6/sitestore/eccc/crd/ccrn/users/scrd107/canesm_runs
assim_sensitivity_root: /home/scrd107/site6